// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-0haXGQ1j620ppeOm9HV5Ltdw-JeF6g',
    appId: '1:822512347396:web:be26430824583b8d1a0851',
    messagingSenderId: '822512347396',
    projectId: 'smart-garden-64cd4',
    authDomain: 'smart-garden-64cd4.firebaseapp.com',
    databaseURL: 'https://smart-garden-64cd4-default-rtdb.firebaseio.com',
    storageBucket: 'smart-garden-64cd4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYR8629dUKlKzgl_A3HRt9fGFMsAT8kYA',
    appId: '1:822512347396:android:24bc57f183405f9e1a0851',
    messagingSenderId: '822512347396',
    projectId: 'smart-garden-64cd4',
    databaseURL: 'https://smart-garden-64cd4-default-rtdb.firebaseio.com',
    storageBucket: 'smart-garden-64cd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFJxbZPdMwn3AJs2vmWQ9fXqmIsht3XaU',
    appId: '1:822512347396:ios:399d7630ba0583b41a0851',
    messagingSenderId: '822512347396',
    projectId: 'smart-garden-64cd4',
    databaseURL: 'https://smart-garden-64cd4-default-rtdb.firebaseio.com',
    storageBucket: 'smart-garden-64cd4.firebasestorage.app',
    iosBundleId: 'com.example.plantapp',
  );

}